version: 1
id: "baseline_comprehensive"
repetitions: 3
metadata:
  system: spark
  system_version: 3.3.4
  table_format: iceberg
  table_format_version: 1.4.3
  benchmark: tpch
  scale_factor: "1"
parameter_values:
  catalog: local
  database: tpch
