version: 1
connection:
  id: duckdb_telemetry
  driver: org.duckdb.DuckDBDriver
  url: jdbc:duckdb:/home/shashank/Link to PDocuments/Capstone/implementation/smoke_test/telemetry.db
execute_ddl: true
ddl_file: '/home/shashank/Link to PDocuments/Capstone/implementation/smoke_test/scripts/ddl.sql'
insert_file: '/home/shashank/Link to PDocuments/Capstone/implementation/smoke_test/scripts/insert.sql'
parameter_values:
  data_path: ''
