import pandas as pd
import numpy as np
import joblib
import json
import os

WORKSPACE_DIR = "/media/shashank/Data1/PDocuments/Capstone/implementation"
PHASE3B_DIR = os.path.join(WORKSPACE_DIR, "scripts/phase3b-predictive-signals")
RESULTS_DIR = os.path.join(PHASE3B_DIR, "results")
ALPHA = 0.05

def conformal_ood():
    print("Loading model and metadata...")
    model = joblib.load(os.path.join(PHASE3B_DIR, "models", "best_regressor.joblib"))
    with open(os.path.join(PHASE3B_DIR, "models", "best_regressor_metadata.json"), 'r') as f:
        meta = json.load(f)
    feature_names = meta['feature_names']
    
    print("Computing q_hat from original calibration set...")
    # Load original dataset to get calibration samples
    orig_df = pd.read_csv(os.path.join(RESULTS_DIR, "dataset_predictive_signals.csv"))
    cal_configs = ["frag200_multi_stream_FIFO", "frag200_multi_stream_FAIR"]
    cal_df = orig_df[orig_df["config_id"].isin(cal_configs)].copy()
    
    # Preprocess cal_df
    X_cal = pd.get_dummies(cal_df, columns=["workload_type", "scheduler_mode", "query"], drop_first=False)
    for col in feature_names:
        if col not in X_cal.columns:
            X_cal[col] = 0
    X_cal = X_cal[feature_names].astype(float)
    y_cal = cal_df["qir_pct"]
    
    # Predict and compute non-conformity scores
    cal_preds = model.predict(X_cal)
    cal_scores = np.abs(y_cal - cal_preds)
    
    n_cal = len(cal_scores)
    q_level = np.ceil((n_cal + 1) * (1 - ALPHA)) / n_cal
    q_level = min(q_level, 1.0)
    
    q_hat = np.quantile(cal_scores, q_level, method='higher')
    print(f"Calibration size: {n_cal}")
    print(f"Computed q_hat: {q_hat:.4f}%")
    
    print("\nApplying conformal bounds to OOD dataset...")
    df = pd.read_csv(os.path.join(RESULTS_DIR, "dataset_ood_predictions.csv")) # Generated by evaluate_ood.py
    
    df["conformal_upper_bound"] = df["predicted_qir_pct"] + q_hat
    df["conformal_lower_bound"] = df["predicted_qir_pct"] - q_hat
    
    # A point is covered if the actual QIR falls within the conformal bounds
    df["is_covered"] = (df["qir_pct"] >= df["conformal_lower_bound"]) & (df["qir_pct"] <= df["conformal_upper_bound"])
    
    overall_coverage = df["is_covered"].mean() * 100.0
    print(f"Overall OOD Empirical Coverage: {overall_coverage:.2f}% (Target: >= {(1-ALPHA)*100:.0f}%)")
    
    # Coverage per frag level
    print("\nCoverage per Fragmentation Level:")
    for frag in sorted(df["frag_level"].unique()):
        subset = df[df["frag_level"] == frag]
        cov = subset["is_covered"].mean() * 100.0
        print(f"  Frag {frag}: {cov:.2f}%")
        
    # Interpolation vs Extrapolation
    inter_df = df[df["ood_type"] == "Interpolation"]
    extra_df = df[df["ood_type"] == "Extrapolation"]
    
    inter_cov = inter_df["is_covered"].mean() * 100.0 if not inter_df.empty else 0.0
    extra_cov = extra_df["is_covered"].mean() * 100.0 if not extra_df.empty else 0.0
    
    print("\nInterpolation vs Extrapolation:")
    print(f"  Interpolation Coverage: {inter_cov:.2f}%")
    print(f"  Extrapolation Coverage: {extra_cov:.2f}%")
    
    # Interval widths
    avg_interval_width = (2 * q_hat)
    avg_actual_range = df["qir_pct"].max() - df["qir_pct"].min()
    print(f"\nAverage Interval Width: {avg_interval_width:.2f}%")
    print(f"Actual QIR Range (OOD): {avg_actual_range:.2f}%")
    
    # Save results
    df.to_csv(os.path.join(RESULTS_DIR, "conformal_ood_results.csv"), index=False)
    
    with open(os.path.join(RESULTS_DIR, "ood_conformal_summary.txt"), "w") as f:
        f.write(f"q_hat: {q_hat}\n")
        f.write(f"overall_coverage: {overall_coverage}\n")
        f.write(f"interpolation_coverage: {inter_cov}\n")
        f.write(f"extrapolation_coverage: {extra_cov}\n")

if __name__ == "__main__":
    conformal_ood()
